### PR TITLE
11 user registration page

### PR DESCRIPTION
**Pull request by Tamrakar182**
- added registration page with subsequent components
- added the alternative loader animation

### CODE REVIEW

**Review by scifisatan — CHANGES_REQUESTED** [review]
Design looking great!

Loader doesn't spin once before loading i think
if it does maybe we need to prolong the animation duration for just a bit more

expected behaviour of form:


https://github.com/user-attachments/assets/e8698bad-91dc-4700-b466-0c73bab2794a

**Comment by Tamrakar182** [comment]
@scifisatan loader ko lagi chai i can artifically introduce a minimum time to show a loading animation but everytime website load huda kheri that would play which wouldnt be good
image

**Comment by scifisatan** [comment]
What if we did the logic like
Is font loaded 
Yes - show website 
No - 0.5 me delay then show website when font loads

**Comment by Tamrakar182** [comment]
that would still mean that the animation is not seen fully, check my recent commit for the behaviour

**Comment by scifisatan** [comment]
user registration animation also looks good

few notes
- change the text on team join
- add loading state on create team or join team button with a spinner.

**Review by scifisatan — CHANGES_REQUESTED** [review]
user registration animation also looks good

few notes

change the text on team join
add loading state on create team or join team button with a spinner.

**Review by scifisatan — APPROVED** [review]
Good work

**Pull request merged**
